# Generated by Django 4.2 on 2023-04-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocTemp',
        ),
    ]
