# Generated by Django 4.1.7 on 2023-04-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_alter_meeting_snt_id"),
        ("docs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doc",
            name="meeting_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="meetings.meeting",
            ),
        ),
    ]
