# Generated by Django 4.1.7 on 2023-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docs", "0003_alter_doc_meeting_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
