# Generated by Django 4.1.7 on 2023-04-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docs", "0005_testdoc_file_testdoc_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestDoc",
        ),
        migrations.RemoveField(
            model_name="doc",
            name="path",
        ),
        migrations.AddField(
            model_name="doc",
            name="file",
            field=models.FileField(default="file", upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
