# Generated by Django 4.2 on 2023-04-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_delete_testdoc_remove_doc_path_doc_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=10)),
            ],
        ),
    ]
