# Generated by Django 4.2 on 2023-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_doctemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctemp',
            name='doc_type',
            field=models.CharField(max_length=50),
        ),
    ]
