# Generated by Django 4.2 on 2023-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_alter_doctemp_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctemp',
            name='doc_type',
            field=models.CharField(max_length=100),
        ),
    ]
