# Generated by Django 4.2 on 2023-04-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_doc_type_alter_doctemp_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='type',
        ),
    ]
