# Generated by Django 4.1.7 on 2023-04-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snts", "0001_initial"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="snt_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="snts.snt"
            ),
        ),
    ]
