# Generated by Django 4.2 on 2023-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_snt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
