# Generated by Django 4.1.7 on 2023-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0003_alter_meeting_snt_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="date",
            new_name="meeting_date",
        ),
        migrations.AddField(
            model_name="meeting",
            name="notification_date",
            field=models.CharField(default="05.05.23", max_length=10),
            preserve_default=False,
        ),
    ]
