# Generated by Django 4.2 on 2023-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='time2',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
