# Generated by Django 4.2 on 2023-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_time2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='notification_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
