# Generated by Django 4.2 on 2023-04-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_rename_notification_date_meeting_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
