# Generated by Django 4.2 on 2023-04-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_alter_meeting_date_alter_meeting_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='place',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='type',
        ),
    ]
