# Generated by Django 4.2 on 2023-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_remove_meeting_place_remove_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
