# Generated by Django 4.1.7 on 2023-04-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_snt",
            name="phone",
            field=models.EmailField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="user_snt",
            name="password",
            field=models.EmailField(max_length=255),
        ),
    ]
