# Generated by Django 4.1.7 on 2023-04-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_alter_meeting_snt_id"),
        ("snts", "0001_initial"),
        ("api", "0005_delete_meeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_snt",
            name="snt_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="snts.snt"
            ),
        ),
        migrations.DeleteModel(
            name="SNT",
        ),
    ]
