# Generated by Django 4.1.7 on 2023-04-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="idk",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="no",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="yes",
            field=models.IntegerField(default=0),
        ),
    ]
