# Generated by Django 4.2 on 2023-04-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_meeting_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='idk',
        ),
        migrations.RemoveField(
            model_name='question',
            name='no',
        ),
        migrations.RemoveField(
            model_name='question',
            name='yes',
        ),
    ]
