# Generated by Django 4.2 on 2023-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_idk_remove_question_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='idk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='yes',
            field=models.IntegerField(default=0),
        ),
    ]
