# Generated by Django 4.2 on 2023-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_ismadepositivedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='decision',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
