# Generated by Django 4.1.7 on 2023-04-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_snt_user_snt_snt_id_alter_snt_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=10)),
                ("date", models.CharField(max_length=10)),
                ("place", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=20)),
                (
                    "snt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.snt"
                    ),
                ),
            ],
        ),
    ]
