# Generated by Django 4.2 on 2023-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_snt_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_snt',
            name='doc_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_snt',
            name='square',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
