# Generated by Django 4.2 on 2023-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_snt_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_snt',
            name='square',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6),
        ),
    ]
